Repository 2110336-SoftwareEngineering2-2021-2/sec2_ChocoTech, pull requests merged in 2022-03, with the labels that each got.

#63 [Feature] Add list page
  apps/doji-frontend/src/pages/list.tsx
Labels: ready to review

#64 [Fix] Payment-related Page
  apps/doji-backend/src/payment/coin-transaction.service.ts
  apps/doji-backend/src/payment/payment.controller.ts
  apps/doji-backend/src/payment/payment.service.ts
  apps/doji-frontend/src/components/TopUpDialog/index.tsx
  apps/doji-frontend/src/modules/payment/attach/credit-card/index.tsx
  apps/doji-frontend/src/modules/payment/select/index.tsx
  apps/doji-frontend/src/pages/balance/index.tsx
  apps/doji-frontend/src/pages/list.tsx
  libs/mui/src/lib/Tables/index.stories.tsx
  libs/mui/src/lib/Tables/index.tsx
  libs/mui/src/lib/Tables/menu.tsx
  yarn.lock
Labels: ready to review

#74 [Breaking Change] Add Google OAuth and Change login auth to use cookie token instead of bearer token
  .env
  .env.compose
  apps/doji-backend/src/admin/admin.controller.ts
  apps/doji-backend/src/auth/auth.controller.ts
  apps/doji-backend/src/auth/auth.dto.ts
  apps/doji-backend/src/auth/auth.module.ts
  apps/doji-backend/src/auth/auth.service.ts
  apps/doji-backend/src/auth/bearer.strategy.ts
  apps/doji-backend/src/auth/cookie.decorator.ts
  apps/doji-backend/src/auth/cookie.strategy.ts
  apps/doji-backend/src/auth/user-auth.guard.ts
  apps/doji-backend/src/auth/user.guard.ts
  apps/doji-backend/src/entities/User.ts
  apps/doji-backend/src/environments/environment.prod.ts
  apps/doji-backend/src/environments/environment.ts
  apps/doji-backend/src/expert/expert.controller.ts
  apps/doji-backend/src/main.ts
  apps/doji-backend/src/messaging/messaging.gateway.ts
  apps/doji-backend/src/payment/payment.controller.ts
  apps/doji-backend/src/profile/profile.controller.ts
  apps/doji-backend/src/register/register.controller.ts
  apps/doji-backend/src/session/session.controller.ts
  apps/doji-backend/src/session/session.service.ts
  apps/doji-backend/src/utils/redis.ts
  apps/doji-backend/src/work-history/work-history.controller.ts
  apps/doji-frontend/src/pages/login/index.tsx
  apps/doji-frontend/src/services/index.ts
  apps/doji-frontend/src/stores/index.ts
  libs/api/src/lib/dtos/auth.ts
  libs/api/src/lib/entities/User.ts
  package.json
  yarn.lock
Labels: ready to review, critical

#73 [Feature] Add reset password via email and email integration with Mailgun
  .env
  .env.compose
  apps/doji-backend/src/admin/admin.controller.ts
  apps/doji-backend/src/assets/reset-password.hbs
  apps/doji-backend/src/auth/auth.controller.ts
  apps/doji-backend/src/auth/auth.dto.ts
  apps/doji-backend/src/auth/auth.module.ts
  apps/doji-backend/src/auth/auth.service.ts
  apps/doji-backend/src/auth/bearer.strategy.ts
  apps/doji-backend/src/auth/cookie.decorator.ts
  apps/doji-backend/src/auth/cookie.strategy.ts
  apps/doji-backend/src/auth/user-auth.guard.ts
  apps/doji-backend/src/auth/user.guard.ts
  apps/doji-backend/src/entities/User.ts
  apps/doji-backend/src/environments/environment.prod.ts
  apps/doji-backend/src/environments/environment.ts
  apps/doji-backend/src/expert/expert.controller.ts
  apps/doji-backend/src/expert/expert.service.ts
  apps/doji-backend/src/main.ts
  apps/doji-backend/src/messaging/messaging.gateway.ts
  apps/doji-backend/src/payment/payment.controller.ts
  apps/doji-backend/src/profile/profile.controller.ts
  apps/doji-backend/src/profile/profile.service.ts
  apps/doji-backend/src/register/register.controller.ts
  apps/doji-backend/src/register/register.service.ts
  apps/doji-backend/src/session/session.controller.ts
  apps/doji-backend/src/session/session.service.ts
  apps/doji-backend/src/utils/redis.ts
  apps/doji-backend/src/work-history/work-history.controller.ts
  apps/doji-backend/src/work-history/work-history.service.ts
  apps/doji-frontend/src/pages/login/index.tsx
  apps/doji-frontend/src/services/index.ts
  apps/doji-frontend/src/stores/index.ts
  libs/api/src/lib/dtos/auth.ts
  libs/api/src/lib/entities/User.ts
  package.json
  yarn.lock
Labels: ready to review

#70 [Fix] authenticate guard logic
  apps/doji-frontend/src/modules/payment/attach/bank-account.tsx
  apps/doji-frontend/src/modules/payment/attach/credit-card/index.tsx
  apps/doji-frontend/src/modules/payment/new/index.tsx
  apps/doji-frontend/src/modules/payment/select/index.tsx
  apps/doji-frontend/src/pages/_app.tsx
  apps/doji-frontend/src/pages/admin/new.tsx
  apps/doji-frontend/src/pages/change-password/index.tsx
  apps/doji-frontend/src/pages/index.tsx
  apps/doji-frontend/src/pages/list.tsx
  apps/doji-frontend/src/pages/login/index.tsx
  apps/doji-frontend/src/pages/privacy-policy.tsx
  apps/doji-frontend/src/pages/profile/index.tsx
  apps/doji-frontend/src/pages/register/[username].tsx
  apps/doji-frontend/src/pages/register/expert.tsx
  apps/doji-frontend/src/pages/register/index.tsx
  apps/doji-frontend/src/pages/session/index.tsx
  apps/doji-frontend/src/pages/terms-of-service.tsx
  apps/doji-frontend/src/pages/work-history/index.tsx
  apps/doji-frontend/src/stores/index.ts
  apps/doji-frontend/src/type.ts
  libs/mui/src/config/theme/components/index.ts
  libs/mui/src/config/theme/components/list.tsx
  libs/mui/src/config/theme/components/menu.tsx
  libs/mui/src/config/theme/components/typography.ts
  libs/mui/src/hooks/index.tsx
  libs/mui/src/index.ts
  libs/mui/src/lib/Logo/index.stories.tsx
  libs/mui/src/lib/Logo/index.tsx
  libs/mui/src/lib/NavBar/constants.ts
  libs/mui/src/lib/NavBar/index.stories.tsx
  libs/mui/src/lib/NavBar/index.tsx
  libs/mui/src/lib/NavBar/styled.tsx
  libs/mui/src/lib/NavBar/types.ts
  libs/mui/src/lib/TopBar/index.tsx
  libs/mui/src/lib/UserBar/index.stories.tsx
  libs/mui/src/lib/UserBar/index.tsx
  libs/mui/src/lib/index.ts
Labels: ready to review

#76 [Fix] Schedule session URL params
  apps/doji-frontend/src/pages/schedule-session/index.tsx
  apps/doji-frontend/src/services/index.ts
Labels: ready to review

#75 [Breaking Change] Fix frontend auth guard method and refactor
  apps/doji-backend/src/app/app.module.ts
  apps/doji-backend/src/auth/auth.controller.ts
  apps/doji-backend/src/auth/auth.dto.ts
  apps/doji-backend/src/auth/auth.exception.ts
  apps/doji-backend/src/auth/auth.module.ts
  apps/doji-backend/src/auth/auth.service.ts
  apps/doji-backend/src/auth/auth.strategy.ts
  apps/doji-backend/src/register/register.controller.ts
  apps/doji-backend/src/register/register.dto.ts
  apps/doji-backend/src/register/register.module.ts
  apps/doji-backend/src/register/register.service.ts
  apps/doji-frontend/src/common/auth/index.tsx
  apps/doji-frontend/src/components/NavigationBar/BottomNav.tsx
  apps/doji-frontend/src/modules/payment/attach/bank-account.tsx
  apps/doji-frontend/src/modules/payment/attach/credit-card/index.tsx
  apps/doji-frontend/src/modules/payment/new/index.tsx
  apps/doji-frontend/src/modules/payment/select/index.tsx
  apps/doji-frontend/src/pages/_app.tsx
  apps/doji-frontend/src/pages/admin/index.tsx
  apps/doji-frontend/src/pages/admin/new.tsx
  apps/doji-frontend/src/pages/balance/index.tsx
  apps/doji-frontend/src/pages/change-password/index.tsx
  apps/doji-frontend/src/pages/create-schedule/index.tsx
  apps/doji-frontend/src/pages/index.tsx
  apps/doji-frontend/src/pages/list.tsx
  apps/doji-frontend/src/pages/login/index.tsx
  apps/doji-frontend/src/pages/my-session/index.tsx
  apps/doji-frontend/src/pages/privacy-policy.tsx
  apps/doji-frontend/src/pages/profile/index.tsx
  apps/doji-frontend/src/pages/session/index.tsx
  apps/doji-frontend/src/pages/signup/[username].tsx
  apps/doji-frontend/src/pages/signup/expert.tsx
  apps/doji-frontend/src/pages/signup/index.tsx
  apps/doji-frontend/src/pages/terms-of-service.tsx
  apps/doji-frontend/src/pages/work-history/index.tsx
  apps/doji-frontend/src/services/fetcher.ts
  apps/doji-frontend/src/services/index.ts
  apps/doji-frontend/src/type.ts
  libs/api/src/index.ts
  libs/api/src/lib/api.spec.ts
  libs/api/src/lib/dtos/auth.ts
  libs/api/src/lib/dtos/register.ts
  libs/api/src/lib/entities/User.ts
  libs/mui/src/lib/TopBar/index.stories.tsx
  libs/mui/src/lib/TopBar/index.tsx
  libs/mui/src/lib/index.ts
  package.json
  yarn.lock
Labels: ready to review

#81 [Fix] Search bar
  apps/doji-frontend/src/pages/list.tsx
  libs/mui/src/lib/SearchBar/index.tsx
Labels: ready to review

#80 [Feature] Add Compact profile and Setting page
  apps/doji-frontend/src/common/auth/index.tsx
  apps/doji-frontend/src/modules/settings/index.tsx
  apps/doji-frontend/src/modules/settings/styled.tsx
  apps/doji-frontend/src/pages/settings/index.tsx
  apps/doji-frontend/src/services/fetcher.ts
  apps/doji-frontend/src/services/index.ts
  libs/mui/src/config/theme/components/index.ts
  libs/mui/src/config/theme/components/list.tsx
  libs/mui/src/lib/CompactProfile/index.stories.tsx
  libs/mui/src/lib/CompactProfile/index.tsx
  libs/mui/src/lib/EditableAvatar/index.stories.tsx
  libs/mui/src/lib/EditableAvatar/index.tsx
  libs/mui/src/lib/NavBar/index.tsx
  libs/mui/src/lib/NavBar/styled.tsx
  libs/mui/src/lib/index.ts
Labels: ready to review

#87 [Fix] Storybook build failed from #85
  apps/doji-frontend/public/static/images/avatar/1.jpg
  apps/doji-frontend/src/components/Card/SessionHistoryCancelButton.tsx
  apps/doji-frontend/src/pages/profile/index.tsx
  apps/doji-frontend/src/pages/session-history/index.tsx
  apps/doji-frontend/src/pages/session/index.tsx
  apps/doji-frontend/src/pages/work-history/index.tsx
  libs/mui/src/index.ts
  libs/mui/src/lib/Session/SessionCard.tsx
  libs/mui/src/lib/Session/SessionHistoryCard.tsx
  libs/mui/src/lib/Session/SessionHistoryCardMenu.tsx
  libs/mui/src/lib/Session/SessionStatusCard.tsx
  libs/mui/src/lib/SessionCard/index.stories.tsx
  libs/mui/src/lib/SessionCard/index.tsx
  libs/mui/src/lib/SessionHistoryCard/components/SessionHistoryCancelButton.tsx
  libs/mui/src/lib/SessionHistoryCard/components/SessionHistoryCardMenu.tsx
  libs/mui/src/lib/SessionHistoryCard/components/SessionStatusCard.tsx
  libs/mui/src/lib/SessionHistoryCard/index.stories.tsx
  libs/mui/src/lib/SessionHistoryCard/index.tsx
  libs/mui/src/lib/index.ts
  libs/mui/src/mockData/index.tsx
  libs/mui/src/mockData/services.tsx
  libs/mui/src/mockData/session-history.tsx
  libs/mui/src/mockData/users.tsx
Labels: ready to review

#93 forgot & reset password frontend functionalities
  apps/doji-frontend/src/pages/forgot-password/index.tsx
  apps/doji-frontend/src/pages/reset-password/[token].tsx
  apps/doji-frontend/src/pages/reset-password/success.tsx
Labels: ready to review, feature

#113 [Fix] Add build storybook in Github Action
  .github/workflows/build-test.yaml
Labels: ready to review

#117 [Feature] Add get all session and schedule endpoint
  apps/doji-backend/src/admin/admin.dto.ts
  apps/doji-backend/src/admin/admin.service.ts
  apps/doji-backend/src/auth/auth.controller.ts
  apps/doji-backend/src/auth/auth.dto.ts
  apps/doji-backend/src/auth/auth.service.ts
  apps/doji-backend/src/auth/auth.strategy.ts
  apps/doji-backend/src/auth/user.guard.ts
  apps/doji-backend/src/entities/Admin.ts
  apps/doji-backend/src/entities/Review.ts
  apps/doji-backend/src/entities/Schedule.ts
  apps/doji-backend/src/entities/Session.ts
  apps/doji-backend/src/entities/User.ts
  apps/doji-backend/src/entities/WorkHistory.ts
  apps/doji-backend/src/expert/expert.controller.ts
  apps/doji-backend/src/expert/expert.dto.ts
  apps/doji-backend/src/expert/expert.service.ts
  apps/doji-backend/src/payment/payment.controller.ts
  apps/doji-backend/src/profile/profile.controller.ts
  apps/doji-backend/src/profile/profile.service.ts
  apps/doji-backend/src/review/review.controller.ts
  apps/doji-backend/src/review/review.service.ts
  apps/doji-backend/src/session/session.controller.ts
  apps/doji-backend/src/session/session.dto.ts
  apps/doji-backend/src/session/session.service.ts
  apps/doji-backend/src/types.ts
  apps/doji-backend/src/utils/redis.ts
  apps/doji-backend/src/work-history/work-history.controller.ts
  apps/doji-backend/src/work-history/work-history.service.ts
  apps/doji-frontend/src/components/Review/RatingEntry.tsx
  apps/doji-frontend/src/pages/session/[id]/index.tsx
  libs/api/src/index.ts
  libs/api/src/lib/dtos/auth.ts
  libs/api/src/lib/dtos/session.ts
  libs/api/src/lib/entities/Report.ts
  libs/api/src/lib/entities/Review.ts
  libs/api/src/lib/entities/Schedule.ts
  libs/api/src/lib/entities/Session.ts
  libs/api/src/lib/entities/User.ts
  libs/mui/src/mockData/services.tsx
  libs/mui/src/mockData/users.tsx
Labels: ready to review

#127 [Fix] Fix UI margin padding
  apps/doji-frontend/src/components/ExpertService/TimePickerController.tsx
  apps/doji-frontend/src/modules/settings/index.tsx
  apps/doji-frontend/src/pages/login/index.tsx
  apps/doji-frontend/src/pages/session/[id]/index.tsx
  apps/doji-frontend/src/pages/session/index.tsx
  apps/doji-frontend/src/pages/session/schedule/[sessionId]/index.tsx
  libs/mui/src/lib/NavBar/index.tsx
  libs/mui/src/lib/SessionCard/index.tsx
Labels: ready to review
